AddDebugPrintsAgent = ["claude-haiku-4-5"]
CRSDiffAgent = ["claude-haiku-4-5"]
CRSDynamicDebugAgent = ["claude-haiku-4-5"]
CRSPovProducerAgent = ["claude-haiku-4-5"]
HarnessInputEncoderAgent = ["claude-haiku-4-5"]
PatcherAgent = ["claude-haiku-4-5"]
SourceQuestionsAgent = ["claude-haiku-4-5"]
TriageAgent = []
# DedupClassifier = ["gpt-4.1-2025-04-14"]
DedupClassifier = ["claude-haiku-4-5"]
FunctionSummarizer = ["claude-haiku-4-5"]
# LikelyVulnClassifier = ["gpt-4.1-2025-04-14"]
LikelyVulnClassifier = ["claude-haiku-4-5"]
CRSVulnAnalyzerAgent = ["claude-haiku-4-5"]
GenerateKaitaiAgent = ["claude-haiku-4-5"]
HarnessInputDecoderAgent = ["claude-haiku-4-5"]
BranchFlipperAgent = ["claude-haiku-4-5"]
LikelyFlippableClassifier = ["claude-haiku-4-5"]
FullModeMulti = ["claude-haiku-4-5"]
FullMode = ["claude-haiku-4-5"]
